---
- name: Verkkopalvelimen konfigurointi
  hosts: app_servers
  become: true
  tasks:
    - name: Odota, että kone on käyttövalmis
      ansible.builtin.import_tasks: tasks/wait_ready.yml

    - name: Asenna ja käynnistä Docker
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Ota sovellus käyttöön
      ansible.builtin.import_tasks: tasks/deploy_app.yml
